language: node_js
node_js:
    - 10
script: yarn lint && yarn && yarn build
deploy:
    provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
        secure: ZW5wnv7VqYpAnGULMzi6o/M8wVd+O3vItecje38A2MgeXBFf8LjeL8Rq3re2wTs+ASekuwJoHKotJukEyPeexm8GUGORjTvUGGkvsWHSSa5Il7uPTazNyWZWglrr9Bis8cdnJNpF4QHcMlf/3OTLM1tjd2Tam8mV2sf6iDxmDIXf1fDYclxVxlV6SAVPlf6ilbGZZFiiKtrndJsYJjPrN/nMeYiuvt6tnQFZmqZJfTlCtMd+z2lgeTk46pjaQvNkpQHSfR+dG1zYzrvTJlRr8mBtsMafP1nCOS5gjYX/sA9DyS8GidIU8tBQpBLPGV+sw3GdPUbfTrKcUuYcn6lGVNdfcvGCgtgyXHdWdzYBS/BYtLNfj5b3MuvVaaVmHy6hkKJ2ScDkMzdJghuH1xtyICZw35kVvpx9yvFjkWXZoIIFbqXWEQpeZJXh1nJtQ6cziskci4iRlFq6VWKxi08wcrFqMCvlSlklEJrlryL3yY5x96OgbAwY9KjKSRAwQpXzv/rbmi+jazRBayo3PsHCcEYT1Nli3/TUtkBFlECg3gnkt2B4uC2AVOrO7KoaHFC0Q37A6CkkcDIzJo0qOxuEM90HhQvM/9t+Qf2zKUa+BWHLJLdPML9FGxw8Ztvdiga5g+RcsikPpq+ppLb+6q0jOltX7arMJwhigeiFpyKghX0=
    on:
        tags: true
        repo: AckeeCZ/antonio
