name: Code Quality Assurance

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '14.x'

            - name: Install dependencies & build packages
              run: yarn install --frozen-lockfile

            - name: Run lint & Type Check
              run: yarn lint && yarn type-check

            - name: Run tests
              run: yarn test:ci
